### ISSUE TITLE
Failing test suite?

### ISSUE THREAD

**Issue by gschorkopf** [tdouce/remote_factory_girl#8]
Hey buddy,

I have 9 failing tests when I install locally.

![screen shot 2014-08-14 at 9 21 06 pm](https://cloud.githubusercontent.com/assets/2623668/3929172/83777d5e-241a-11e4-9e61-adeb3720f069.png)

Thoughts?

**Comment by iamvery** [comment]
I believe this is due to rspec 3's use of `be_truthy/falsey`. The true/false flavors were deprecated pre 3.0. See https://github.com/rspec/rspec-expectations/issues/283

**Comment by tdouce** [comment]
Yep, good :eyeglasses:. @gschorkopf fixed this! :+1:
